export const JTA_DATA = [
  {
    id: "1",
    name: "Ramesh Adhikari",
    qualification: "BSc Agriculture",
    phone: "+977 980-598-1168",
    profilePicture: "https://randomuser.me/api/portraits/men/32.jpg",
    field: "Agriculture",
    isOnline: true,
    rating: 4.8,
    experience: 5,
    specialization: "Crop Management",
    languages: ["Nepali", "English"],
    responseTime: "Usually responds in 15 mins"
  },
  {
    id: "2",
    name: "Sita Koirala",
    qualification: "BSc Veterinary Science",
    phone: "+977 980-568-1157",
    profilePicture: "https://randomuser.me/api/portraits/women/44.jpg",
    field: "Veterinary",
    isOnline: true,
    rating: 4.9,
    experience: 7,
    specialization: "Animal Health",
    languages: ["Nepali", "Maithili"],
    responseTime: "Usually responds in 10 mins"
  },
  {
    id: "3",
    name: "Bikash Sharma",
    qualification: "MSc Agriculture (Horticulture)",
    phone: "+977 980-245-7152",
    profilePicture: "https://randomuser.me/api/portraits/men/55.jpg",
    field: "Agriculture",
    isOnline: false,
    rating: 4.6,
    experience: 4,
    specialization: "Fruit Cultivation",
    languages: ["Nepali", "Hindi","Maithili"],
    responseTime: "Usually responds in 30 mins"
  },
  {
    id: "4",
    name: "Anita Thapa",
    qualification: "BVSc & AH",
    phone: "+977 982-457-1154",
    profilePicture: "https://randomuser.me/api/portraits/women/65.jpg",
    field: "Veterinary",
    isOnline: true,
    rating: 4.7,
    experience: 6,
    specialization: "Poultry Farming",
    languages: ["Nepali", "Newari"],
    responseTime: "Usually responds in 5 mins"
  },
  {
    id: "5",
    name: "Kiran Poudel",
    qualification: "Diploma in Agriculture",
    phone: "+977 970-124-8751",
    profilePicture: "https://randomuser.me/api/portraits/men/71.jpg",
    field: "Agriculture",
    isOnline: false,
    rating: 4.5,
    experience: 3,
    specialization: "Organic Farming",
    languages: ["Nepali"],
    responseTime: "Usually responds in 45 mins"
  },
  {
    id: "6",
    name: "Mina Gurung",
    qualification: "MSc Animal Science",
    phone: "+977 981-234-5678",
    profilePicture: "https://randomuser.me/api/portraits/women/33.jpg",
    field: "Veterinary",
    isOnline: true,
    rating: 4.9,
    experience: 8,
    specialization: "Dairy Farming",
    languages: ["Nepali", "Gurung", "English"],
    responseTime: "Usually responds in 8 mins"
  },
  {
    id: "7",
    name: "Rajendra Bhandari",
    qualification: "PhD Agriculture",
    phone: "+977 984-123-4567",
    profilePicture: "https://randomuser.me/api/portraits/men/68.jpg",
    field: "Agriculture",
    isOnline: true,
    rating: 5.0,
    experience: 12,
    specialization: "Soil Science",
    languages: ["Nepali", "English", "Hindi"],
    responseTime: "Usually responds in 20 mins"
  },
  {
    id: "8",
    name: "Sunita Rai",
    qualification: "BSc Veterinary Medicine",
    phone: "+977 985-678-9012",
    profilePicture: "https://randomuser.me/api/portraits/women/22.jpg",
    field: "Veterinary",
    isOnline: false,
    rating: 4.4,
    experience: 2,
    specialization: "Pet Care",
    languages: ["Nepali", "Rai","English"],
    responseTime: "Usually responds in 60 mins"
  }
];